ruby/rails/simple/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

ruby/rails/simple/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/rails/simple/app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  field :name, type: String

  belongs_to :user

end

ruby/rails/simple/app/models/user.rb
class User
  include Mongoid::Document
  extend Enumerize

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :name,    type: String

  field :role
  enumerize :role,
            in: [:guest, :user, :admin],
            default: :guest,
            scope: true

  mount_uploader :avatar, AvatarUploader

  has_many :articles

  RailsAdmin.config do |config|
    config.model 'User' do
      list do
        field :name
        field :email
        field :role
      end
    end
  end

end

ruby/rails/simple/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ruby/rails/simple/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    puts "home.index"
    Article.new(name: "new article").save()
    @articles = Article.all()
    puts @articles
    puts I18n.t 'hello'
    I18n.locale = :"zh-CN"
    puts I18n.t 'hello'
  end
end

ruby/rails/simple/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/rails/simple/app/views/home/index.html.slim
div= "hello world"
- @articles.each do |article|
  div
    span= article._id
    span &nbsp;
    span= article.name
end

ruby/rails/simple/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div>
        <span><%= current_user.email %></span>
        <span><%= link_to "注销", destroy_user_session_path, :method => :delete%></span>
        <% if current_user.role == "admin" %>
            <span><%= link_to "后台管理", rails_admin_path %></span>
        <% end  %>
      </div>
    <% else %>
      <div>
        <span><%= link_to "登录",new_user_session_path %></span>
      </div>
    <% end  %>
    <%= yield %>
  </body>
</html>